base_columns:
  - Date
  - Close
  - Market Returns
  - Signal
  - In Position
  - No of Shares
  - Balance
  - Realized PnL
  - Unrealized PnL
  - Total Strategy Portfolio Value
  - Buy and Hold Portfolio Value
  - Strategy Drawdown
  - Strategy Max Drawdown
  - Buy and Hold Drawdown
  - Buy and Hold Max Drawdown

symbols:
  - META
  - AAPL
  - AMZN
  - NFLX
  - GOOGL